#!/bin/bash
#SBATCH -A IscrC_H-CNT
#SBATCH -p m100_usr_prod
###SBATCH --qos=m100_qos_dbg
#SBATCH --time 23:59:59
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gpus-per-node=1
#SBATCH --mem=230000
#SBATCH --job-name=dpGTrain
#SBATCH -e JOB.e
#SBATCH -o JOB.o

module purge
module load profile/deeplrn
module load autoload deepmd/2.0

export OMP_NUM_THREADS=16
export TF_INTRA_OP_PARALLELISM_THREADS=16
export TF_INTER_OP_PARALLELISM_THREADS=2

srun dp train $1/input.json 
#dp train  --restart model.ckpt  input.json
srun dp freeze -o $1/graph.pb
srun dp compress -i $1/graph.pb -o $1/compressed.pb -t $1/input.json
