#!/bin/bash
#SBATCH --err=JOB.e
#SBATCH --out=JOB.o
#SBATCH -A IscrC_H-CNT
#SBATCH -p m100_usr_prod
#SBATCH --qos=m100_qos_dbg
#SBATCH --time=01:55:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --mem=240G
#SBATCH --job-name=dpGen-SCF

module load profile/chem-phys
module load autoload qe-gpu/7.1

export OMP_NUM_THREADS=8

###mpirun -gpu -np 4 --map-by socket:PE=4 --rank-by core pw.x -nk 4 -input Fe110+3AP+Fe110_5GPa-800K_931400.pwi >> Fe110+3AP+Fe110_5GPa-800K_931400.pwo

mpirun -gpu -np 4 pw.x -nk 2 -input $1 >> $2
